# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sql_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(568, 444)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget_sqlData = QtWidgets.QListWidget(Dialog)
        self.listWidget_sqlData.setObjectName("listWidget_sqlData")
        self.horizontalLayout.addWidget(self.listWidget_sqlData)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_loadSqlData = QtWidgets.QPushButton(Dialog)
        self.pushButton_loadSqlData.setObjectName("pushButton_loadSqlData")
        self.verticalLayout.addWidget(self.pushButton_loadSqlData)
        self.pushButton_togglaSqlData = QtWidgets.QPushButton(Dialog)
        self.pushButton_togglaSqlData.setObjectName("pushButton_togglaSqlData")
        self.verticalLayout.addWidget(self.pushButton_togglaSqlData)
        self.pushButton_delectSqlData = QtWidgets.QPushButton(Dialog)
        self.pushButton_delectSqlData.setObjectName("pushButton_delectSqlData")
        self.verticalLayout.addWidget(self.pushButton_delectSqlData)
        self.listView_cameraParm = QtWidgets.QListView(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_cameraParm.sizePolicy().hasHeightForWidth())
        self.listView_cameraParm.setSizePolicy(sizePolicy)
        self.listView_cameraParm.setObjectName("listView_cameraParm")
        self.verticalLayout.addWidget(self.listView_cameraParm)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_loadSqlData.setText(_translate("Dialog", "读取已存数据"))
        self.pushButton_togglaSqlData.setText(_translate("Dialog", "切换为选中的文件"))
        self.pushButton_delectSqlData.setText(_translate("Dialog", "删除选中的文件"))
